wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    code_path: code/agar/workspace.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 1
      - 3
      4: 3.8.8
      5: 0.11.2
      8:
      - 3
      - 5
env_name:
  desc: null
  value: agar
policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 25000
